services:
  # ============= Backend Express (Web Service) =============
  - type: web
    name: myapp-api
    env: node
    rootDir: server
    region: frankfurt
    buildCommand: npm ci --omit=dev
    startCommand: node index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "https://myapp-web.onrender.com"

  # ============= Frontend React (Static Site) =============
  - type: web
    name: myapp-web
    env: static
    rootDir: .
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
    envVars:
      - key: VITE_API_BASE
        value: "https://myapp-api.onrender.com"
