services:
  # ============= Backend Express (Web Service) =============
  - type: web
    name: myapp-api
    env: node
    rootDir: server
    plan: free
    region: frankfurt
    buildCommand: npm ci --omit=dev
    startCommand: node index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      # Ajoute DATABASE_URL manuellement après création (Neon)
      - key: CORS_ORIGIN
        value: "*"

  # ============= Frontend React (Static Site) =============
  - type: web
    name: myapp-web
    env: static
    rootDir: .
    plan: free
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: myapp-api
          property: url
